FROM node:22-alpine as builder

ENV NODE_ENV development

# Update and install dependencies
RUN apk update && apk upgrade
RUN apk add git openssh-client

# Create destination directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json .
RUN npm install && npm cache clean --force

EXPOSE 3000

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# Specify the volume for development sync
VOLUME /usr/src/app

CMD ["npm", "run", "dev"]
