FROM node:22-alpine as builder

ENV NODE_ENV production

# Update and install dependencies
RUN apk update && apk upgrade
RUN apk add git

# Create destination directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json .
RUN npm install && npm cache clean --force

COPY . .

RUN npm run generate


FROM nginx:stable-alpine as production-stage

COPY --from=builder /usr/src/app/.output/public /usr/share/nginx/html

COPY --from=builder /usr/src/app/nginx.conf /etc/nginx/nginx.conf

RUN chown -R nginx:nginx /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
